### ISSUE TITLE
The elevation angle of test dataset

### ISSUE THREAD

**Issue by ymingxie** [yanqinJiang/Consistent4D#10]
Hi, 

The elevation angle for all 7 objects in the test dataset is 0 right?

Thanks

**Comment by yanqinJiang** [comment]
The camera elevation angle is indeed 0. 
But it is possible that I rotate some objects to make sure they fit the camera view. So maybe the relative elevation angle is not 0.  
Sorry I can't remember the details.

**Comment by ymingxie** [comment]
Thanks
