### ISSUE TITLE
Time to release the code

### ISSUE THREAD

**Issue by XinyangHan** [yanqinJiang/Consistent4D#2]
Thanks for your awesome work! May I ask what might be the expected day for the code to release? That would be really helpful!

**Comment by yanqinJiang** [comment]
Thanks for your interest in our work! 
Hopefully, the code will be released this weekend. No later than next Tuesday. Please Stay tuned : )

**Comment by yanqinJiang** [comment]
All the codes are released! Thanks for your interested in our work!
Feel free to open an issue if you meet any problem when using our code.  &#x1F917;
