### ISSUE TITLE
flownet.pkl

### ISSUE THREAD

**Issue by Zerg-Overmind** [yanqinJiang/Consistent4D#3]
Hi, just a kind remind that flownet.pkl you have uploaded seems to be a wrong version. Also, the latest version of in [RIFE](https://github.com/hzwer/Practical-RIFE) has different model size with the one used in your code. Instead, v4.6 - 2022.9.26 (and before) works for me.

**Comment by yanqinJiang** [comment]
Thanks for your feedback! I did use the v4.6-2022.9.26 version of RIFE in my experiments. 
I compare the checkpoint I uploaded to google drive with the version provided in RIFE repo and find they seem to be the same. (I have to tell I download the model from google drive link in RIFE, not 百度网盘. But I guess they contain the same model weight.）

I haven't tested the latest version of RIFE, and the latest version might require some modification to the codes
. I'll test it in my free time. Hope that it will have better performance.
