### ISSUE TITLE
uids of the objects in test dataset

### ISSUE THREAD

**Issue by ymingxie** [yanqinJiang/Consistent4D#9]
Hi, thanks for this excellent work.  

Is it possible to share the uids of these 7 objects in the test dataset?

**Comment by yanqinJiang** [comment]
I forgot uids of those objects. But I have zip files of them. If you need, I can send them to you via e-mail.

**Comment by ymingxie** [comment]
Is the zip file the same as https://drive.google.com/file/d/1jn18kA2FfKMnyQ6fisIn8rhBI0dr3NFk/view ? 
if not, please send them via email! My email is ymxyimingxie@gmail.com 

Thanks!
